### ISSUE TITLE
Can you add experimental result files based on T5 backbone？

### ISSUE THREAD

**Issue by 20174376** [codesedoc/DMSR#1]
I notice that the paper presented experimental results on T5 and BART, may you add experimental result files based on T5 backbone？Thanks a lot.

**Comment by codesedoc** [comment]
The baseline experimental results are referred to the related work.
Please check the [paper](https://aclanthology.org/2022.acl-long.257) and its source [code](https://github.com/SALT-NLP/positive-frames). Thanks!

**Comment by 20174376** [comment]
You seem to have misunderstood my meaning. I was wondering if you could provide the generated files for pg2st-t5 and st2pg-t5? Sincere thanks!

**Comment by codesedoc** [comment]
Oh! so sorry for mistake, now the results obtained based on T5 are avilable. Thanks!
